/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario.vista;

import inventario.controlador.CMayorista;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgarcastro
 */
public class VMayorista extends javax.swing.JFrame {

    /**
     * Creates new form VMayorista
     */
    public VMayorista() {
        initComponents();
        setLocationRelativeTo(null);
        this.lInventario.setText("");
        this.lPedido.setText("");
        this.lDiaActual.setText("");
        this.lNumClientes.setText("");
        this.lFalta.setText("");
    }
    
    public void actualizarCliente(List clientes){
        this.lNumClientes.setText(""+clientes.size());
    }
    
    public void mostrarDia(int dia){
        this.lDiaActual.setText(""+dia);
    }
    
    public void mostrarStock(int cantidad, int faltantes){
        this.lInventario.setText(""+cantidad);
        this.lFalta.setText(""+faltantes);
    }
    
    public void mostrarOrdenes(Object[][] datos, int tam) {
        tOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Id Minorista", "Cantidad", "Dias de espera", "Aceptado", "Entregado"
            }));
        DefaultTableModel temp = (DefaultTableModel) tOrdenes.getModel();
        for (int i = 0; i < tam; i++) {
            temp.addRow(datos[i]);
        }
    }
    
    public void mostrarMinoristas(List<String> minoristas) {
        tMinoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Id", "Minorista"
            }));
        DefaultTableModel temp = (DefaultTableModel) tMinoristas.getModel();
        Object[] fila = new Object[]{};
        for (int i = 0; i < minoristas.size(); i++) {
            if(minoristas.get(i).equals("H"))
                fila = new Object[]{i,"Humano"};
            if(minoristas.get(i).equals("S"))
                fila = new Object[]{i,"Simulado"};
            temp.addRow(fila);
        }
    }
    
    public void mostrarMiPedido(int cantidad, int diasEspera){
        if(cantidad == 0 && diasEspera == 0)
            this.cTengoPedido.setSelected(false);
        else{
            this.cTengoPedido.setSelected(true);
            this.lPedido.setText("<html>Cantidad: "+cantidad+"<br>Dias de Espera: "+diasEspera+"</html>");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lPuerto = new javax.swing.JLabel();
        tPuerto = new javax.swing.JTextField();
        bIniciar = new javax.swing.JButton();
        lClientes = new javax.swing.JLabel();
        lNumClientes = new javax.swing.JLabel();
        lP = new javax.swing.JLabel();
        tP = new javax.swing.JTextField();
        lQ = new javax.swing.JLabel();
        tQ = new javax.swing.JTextField();
        BSgteDia = new javax.swing.JButton();
        lDia = new javax.swing.JLabel();
        lDiaActual = new javax.swing.JLabel();
        lStock = new javax.swing.JLabel();
        lInventario = new javax.swing.JLabel();
        sOrdenes = new javax.swing.JScrollPane();
        tOrdenes = new javax.swing.JTable();
        bAuto = new javax.swing.JButton();
        sMinoristas = new javax.swing.JScrollPane();
        tMinoristas = new javax.swing.JTable();
        cTengoPedido = new javax.swing.JCheckBox();
        lPedido = new javax.swing.JLabel();
        bDiaAuto = new javax.swing.JButton();
        lFaltantes = new javax.swing.JLabel();
        lFalta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAYORISTA");
        setResizable(false);

        lPuerto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lPuerto.setText("Puerto:");

        bIniciar.setText("Iniciar");
        bIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarActionPerformed(evt);
            }
        });

        lClientes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lClientes.setText("Número de  Minoristas:");

        lNumClientes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lNumClientes.setText("###");

        lP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lP.setText("p:");

        tP.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lQ.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lQ.setText("q:");

        tQ.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        BSgteDia.setText("Siguiente Dia");
        BSgteDia.setEnabled(false);
        BSgteDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSgteDiaActionPerformed(evt);
            }
        });

        lDia.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lDia.setText("Dia actual: ");

        lDiaActual.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lDiaActual.setText("###");

        lStock.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lStock.setText("Inventario:");

        lInventario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lInventario.setText("####");

        tOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Minorista", "Cantidad", "Dias de espera", "Aceptado", "Entregado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tOrdenes.setEnabled(false);
        sOrdenes.setViewportView(tOrdenes);

        bAuto.setText("Auto");
        bAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAutoActionPerformed(evt);
            }
        });

        tMinoristas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Minorista"
            }
        ));
        tMinoristas.setEnabled(false);
        sMinoristas.setViewportView(tMinoristas);

        cTengoPedido.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cTengoPedido.setText("Tengo un pedido");
        cTengoPedido.setEnabled(false);
        cTengoPedido.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cTengoPedidoStateChanged(evt);
            }
        });

        lPedido.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lPedido.setText("<html>\nCantidad: \n<br>\nDias de espera: \n</html>");

        bDiaAuto.setText("Auto");
        bDiaAuto.setEnabled(false);
        bDiaAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDiaAutoActionPerformed(evt);
            }
        });

        lFaltantes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lFaltantes.setText("Faltantes:");

        lFalta.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lFalta.setText("###");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lFaltantes)
                                    .addComponent(lStock))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lFalta)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lQ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tQ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bIniciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bAuto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lPuerto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cTengoPedido)
                                    .addComponent(lPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lDia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lDiaActual))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(BSgteDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bDiaAuto)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sMinoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lNumClientes)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(sMinoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lClientes)
                    .addComponent(lNumClientes))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPuerto)
                    .addComponent(tPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lP)
                    .addComponent(tP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQ)
                    .addComponent(tQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bIniciar)
                    .addComponent(bAuto))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStock)
                    .addComponent(lInventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFaltantes)
                    .addComponent(lFalta))
                .addGap(18, 18, 18)
                .addComponent(cTengoPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDia)
                    .addComponent(lDiaActual))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSgteDia)
                    .addComponent(bDiaAuto))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarActionPerformed
        CMayorista.iniciarServidor(Integer.parseInt(this.tP.getText()), Integer.parseInt(this.tQ.getText()), Integer.parseInt(this.tPuerto.getText()));
        this.tP.setEditable(Boolean.FALSE);
        this.tP.setEnabled(Boolean.FALSE);
        this.tQ.setEditable(Boolean.FALSE);
        this.tQ.setEnabled(Boolean.FALSE);
        this.tPuerto.setEditable(Boolean.FALSE);
        this.tPuerto.setEnabled(Boolean.FALSE);
        this.BSgteDia.setEnabled(true);
        this.bDiaAuto.setEnabled(true);
    }//GEN-LAST:event_bIniciarActionPerformed

    private void BSgteDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSgteDiaActionPerformed
        CMayorista.siguienteDia();
    }//GEN-LAST:event_BSgteDiaActionPerformed

    private void bAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAutoActionPerformed
        this.tP.setText(""+100);
        this.tQ.setText(""+500);
        this.tPuerto.setText(""+5555);
        bIniciarActionPerformed(evt);
    }//GEN-LAST:event_bAutoActionPerformed

    private void cTengoPedidoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cTengoPedidoStateChanged
        if(!this.cTengoPedido.isSelected())
            this.lPedido.setText("");
    }//GEN-LAST:event_cTengoPedidoStateChanged

    private void bDiaAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDiaAutoActionPerformed
        CMayorista.diaAuto();
    }//GEN-LAST:event_bDiaAutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMayorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMayorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMayorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMayorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMayorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSgteDia;
    private javax.swing.JButton bAuto;
    private javax.swing.JButton bDiaAuto;
    private javax.swing.JButton bIniciar;
    private javax.swing.JCheckBox cTengoPedido;
    private javax.swing.JLabel lClientes;
    private javax.swing.JLabel lDia;
    private javax.swing.JLabel lDiaActual;
    private javax.swing.JLabel lFalta;
    private javax.swing.JLabel lFaltantes;
    private javax.swing.JLabel lInventario;
    private javax.swing.JLabel lNumClientes;
    private javax.swing.JLabel lP;
    private javax.swing.JLabel lPedido;
    private javax.swing.JLabel lPuerto;
    private javax.swing.JLabel lQ;
    private javax.swing.JLabel lStock;
    private javax.swing.JScrollPane sMinoristas;
    private javax.swing.JScrollPane sOrdenes;
    private javax.swing.JTable tMinoristas;
    private javax.swing.JTable tOrdenes;
    private javax.swing.JTextField tP;
    private javax.swing.JTextField tPuerto;
    private javax.swing.JTextField tQ;
    // End of variables declaration//GEN-END:variables
}
